# ----
# Site

title: Cocoa Art Chocolates
url: "sweetamanda.netlify.com"
location: "São Bernardo do Campo, São Paulo, Brasil"

baseurl:
google_analytics_key:
newsletter_action:
disqus_shortname:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Cocoa Art Chocolates - chocolates finos e ovos de páscoa
author:
  name: Amanda Borges
  email: albnutri@gmail.com
  twitter:
  instagram: cocoa.art.chocolates

social:
  name: Cocoa Art Chocolates
  links:
    - https://github.com/agaelebe/treat-jekyll-template

# -----
# Build

timezone: Etc/UTC-3

paginate: 10
paginate_path: "/:num/"
permalink: /:categories/:title:output_ext

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      push_sidebar_down: true
      print_stylesheet: true
      comments: true
      _options:
        content:
          width: 1560
          height: 2000
        featured_image:
          width: 1560
          height: 2000
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"
      push_sidebar_down: true

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -----------
# CloudCannon

social_icons:
  - Instagram
  - RSS

_options:
  author_image:
    width: 400
    height: 400